version: "3"

services:
  weatherapp:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./weatherApp:/weatherApp
    command: >
      - sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=weatherapp
      - DB_USER=postgres
      - DB_PASS=supersecretepassword
    depends_on:
      - db
  db:
    image: postgress:11-alpine
    environment:
      - POSTGRES_DB=weatherapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretepassword
