version: "3"

services:
  weatherapp:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./weatherApp:/weatherApp
    command: >
      - sh -c "python manage.py runserver 0.0.0.0:8000"
